"""add_forensic_report_url_to_batches

Revision ID: 8f4a8d6faf0b
Revises: 3a6969760d59
Create Date: 2026-03-11 16:40:22.787871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4a8d6faf0b'
down_revision: Union[str, Sequence[str], None] = '3a6969760d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('forensic_report_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'forensic_report_url')
    # ### end Alembic commands ###
