"""consumer_traceability_metrics

Revision ID: b1ba766dc213
Revises: 8f4a8d6faf0b
Create Date: 2026-03-12 01:54:36.258097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1ba766dc213'
down_revision: Union[str, Sequence[str], None] = '8f4a8d6faf0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('farms', sa.Column('acreage', sa.String(length=100), nullable=True))
    op.add_column('farms', sa.Column('npk_ratio', sa.String(length=50), nullable=True))
    op.add_column('farms', sa.Column('farming_technology', sa.String(length=255), nullable=True))
    op.add_column('ingredients', sa.Column('procurement_details', sa.Text(), nullable=True))
    op.add_column('ingredients', sa.Column('key_benefits_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'key_benefits_json')
    op.drop_column('ingredients', 'procurement_details')
    op.drop_column('farms', 'farming_technology')
    op.drop_column('farms', 'npk_ratio')
    op.drop_column('farms', 'acreage')
    op.drop_column('farmers', 'about')
    # ### end Alembic commands ###
