"""add_coa_to_recipe_ingredients

Revision ID: c2bff4a8a984
Revises: b1ba766dc213
Create Date: 2026-03-12 18:15:32.381336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bff4a8a984'
down_revision: Union[str, Sequence[str], None] = 'b1ba766dc213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('coa_status', sa.Enum('AVAILABLE', 'PENDING', 'NOT_REQUIRED', name='coastatus', create_constraint=False), nullable=False, server_default='PENDING'))
    op.add_column('recipe_ingredients', sa.Column('coa_link', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'coa_link')
    op.drop_column('recipe_ingredients', 'coa_status')
    # ### end Alembic commands ###
