version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: purferme_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    networks:
      - purferme_network

networks:
  purferme_network:
    external: true
    name: traceability_backend_purferme_network
